import type { NextPage } from 'next'
import { useQuery } from '@apollo/client'
import Head from 'next/head'
import TicketList from '../../components/ticket/TicketList'
import BaseLayout from '../../layout/BaseLayout'
import { GET_TICKETS } from '../../apollo/queries'


const ListTaskPage: NextPage = () => {
	const { loading, error, data } = useQuery(GET_TICKETS)

	return (
		<div className={'flex min-h-screen flex-col justify-between bg-gray-50'}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				{/* 	<link rel='stylesheet' href='https://rsms.me/inter/inter.css' /> */}
			</Head>
			<BaseLayout name={'Liste des Tickets'}>
				<>
					{loading && <p> En cours de chargement...</p>}
					{error && error.graphQLErrors.map(({ message }, i) => (
         		 <span key={i}>{message}</span>
       		))}
					{!loading && !error && <TicketList tickets={data.tickets} />}
				</>
			</BaseLayout>
		</div>
	)
}
export default ListTaskPage
