import type { NextPage } from 'next'
import { gql, useQuery } from '@apollo/client'
import Head from 'next/head'
import TicketList from '../../components/ticket/TicketList'
import BaseLayout from '../../layout/BaseLayout'

export const GET_TICKETS = gql`
	query Tickets {
		tickets {
			id
			title
			description
			status
			createdAt
		}
	}
`
const ListTaskPage: NextPage = () => {
	const { loading, error, data } = useQuery(GET_TICKETS)

	return (
		<div className={'flex min-h-screen flex-col justify-between bg-gray-50'}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				{/* 	<link rel='stylesheet' href='https://rsms.me/inter/inter.css' /> */}
			</Head>
			<BaseLayout
				name={'Liste des Tickets'}
				button={<button>Ajouter un ticket</button>}
			>
				<>
					{loading && <p> En cours de chargement...</p>}
					{error && <p>'Une erreur est survenue'</p>}
					{!loading && !error && <TicketList tickets={data.tickets} />}
				</>
			</BaseLayout>
		</div>
	)
}
export default ListTaskPage
