name: Compile and push client image

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx

      - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: ../2203-wns-etchebest-tfs-front/
          file: ../2203-wns-etchebest-tfs-front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tfs_deploy_client_prod:latest
